[result]
dir = "dymola-ci-tests/result"
whitelist_dir = "dymola-ci-tests/result/ci_whitelist"
config_dir = "dymola-ci-tests/result/configfiles"
plot_dir = "dymola-ci-tests/result/charts"
syntax_dir = "dymola-ci-tests/result/syntax"
regression_dir = "dymola-ci-tests/result/regression"
interact_ci_dir = "dymola-ci-tests/result/interact_CI"
ci_template_dir = "dymola-ci-tests/result/ci_template"
check_result_dir = "dymola-ci-tests/result/Dymola_check"
OM_check_result_dir = "dymola-ci-tests/result/OM_check"

[color]
CRED = "\\033[91m"
CEND = "\\033[0m"
green = "\\033[0;32m"
yellow = "\\033[33m"
blue = "\\033[44m"

[config_ci]
dir = "dymola-ci-tests/Configfiles"
exit_file = "dymola-ci-tests/Configfiles/exit.sh"
new_ref_file = "dymola-ci-tests/Configfiles/ci_new_ref_file.txt"
new_create_ref_file = "dymola-ci-tests/Configfiles/ci_new_created_reference.txt"
changed_file = "dymola-ci-tests/Configfiles/ci_changed_model_list.txt"
ref_file = "dymola-ci-tests/Configfiles/ci_reference_list.txt"
eof_file = "dymola-ci-tests/Configfiles/EOF.sh"

[whitelist]
ci_dir = "dymola-ci-tests/ci_whitelist"
model_file = "dymola-ci-tests/ci_whitelist/ci_check_whitelist.txt"
simulate_file = "dymola-ci-tests/ci_whitelist/ci_simulate_whitelist.txt"
html_file = "dymola-ci-tests/ci_whitelist/ci_html_whitelist.txt"
ref_file = "dymola-ci-tests/ci_whitelist/ci_reference_check_whitelist.txt"
