from ModelicaPyCI.load_global_config import CI_CONFIG
from pathlib import Path
from mako.template import Template
import os
from ModelicaPyCI.utils import logger


def create_index_html():
    all_files = []
    results_dir = CI_CONFIG.get_file_path("result")
    for subdir, dirs, files in os.walk(results_dir):
        for file in files:
            filepath = Path(subdir, file)
            all_files.append(filepath)
    if len(all_files) == 0:
        logger.info('No files to display')
    else:
        logger.info("Found %s files", len(all_files))
        template_str = """
      <!doctype html>
        <html>
          <head>
            <link rel="stylesheet" href="style.css">
            <meta charset="UTF-8">
            <title>Files generated by CI</title>
          </head>
          <body>
            <header>
    	  %for file in all_files:
    	      <br><li><a href="${file}" target="content">${file}</a></li></br>
    	  %endfor
            </header>

          </body>
        </html>
    """
        index_html = Template(template_str).render(all_files=all_files)
        index_html_path = results_dir.joinpath("index.html")
        with open(index_html_path, "w") as file_tmp:
            file_tmp.write(index_html)


if __name__ == '__main__':
    create_index_html()
